# This workflow will build and push a new container image to Amazon ECR,
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an ECR repository to store your images.
#    For example: `aws ecr create-repository --repository-name my-ecr-repo --region us-east-2`.
#    Replace the value of the `ECR_REPOSITORY` environment variable in the workflow below with your repository's name.
#    Replace the value of the `AWS_REGION` environment variable in the workflow below with your repository's region.
#
# 2. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.

name: Deploy to DEV

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-2 # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: 445567071754.dkr.ecr.us-east-2.amazonaws.com/myecr-repo # set this to your Amazon ECR repository name
  IMAGE_TAG: ${{ github.sha }}
permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Deploy
    runs-on: ["self-hosted", "dev"]

    steps:
      #- name: clean up workspace
      #run: |
      #sudo chmod 755 /home/ubuntu/core-service-actions-runner/_work/core-services/core-services/
      #sudo rm -rf /home/ubuntu/core-service-actions-runner/_work/core-services/core-services/.scannerwork
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: 445567071754.dkr.ecr.us-east-2.amazonaws.com/myecr-repo

        run: |

          docker build --build-arg NPM_AUTH_TOKEN=${{ secrets.NPM_AUTH_TOKEN }} -t $ECR_REGISTRY:core-app-v1 -f container/Dockerfile.app . --no-cache

          docker build -t $ECR_REGISTRY:core-api-v1 -f container/Dockerfile.api . --no-cache

          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 445567071754.dkr.ecr.us-east-2.amazonaws.com

          docker push $ECR_REGISTRY:core-api-v1
          docker push $ECR_REGISTRY:core-app-v1
      # - name: building Container
      #   run: |
      #     sudo cp /home/ubuntu/micro-service-dev/docker-compose.yml .
      #     docker-compose -f docker-compose.yml up -d | echo y
